version: "3"

services:
  php:
    build:
      context: src
      dockerfile: ../Dockerfile
    ports:
      - "0.0.0.0:80:80"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - pweb
    environment:
      PHP_IDE_CONFIG: 'serverName=docker'
      XDEBUG_CONFIG: 'client_host=${DOCKER_GATEWAY_HOST:-host.docker.internal} client_port=9003 log_level=0'
      XDEBUG_MODE: 'debug,develop'
      DB_HOST: db
      DB_USER: root
      DB_NAME: sistema
      DB_PORT: 3306
    volumes:
      - ./src/:/var/www/html/
      - ./docker/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    depends_on:
      - db
  db:
    image: mariadb:10
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: sistema
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - pweb
    volumes:
      - database:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p" ]
      retries: 3
      timeout: 5s
  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - pweb
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: root
      PMA_PASSWORD:
    depends_on:
      - db

networks:
  pweb:
    driver: bridge

volumes:
  database:
    driver: local
